config/routes.rb
Rails.application.routes.draw do

  get 'redemptions/edit_discount' => 'redemptions#edit_discount', as: :edit_discount
  put 'redemptions/update_discount' => 'redemptions#update_discount', as: :update_discount
  resources :redemptions

  resources :purchases

  resources :adjustments

  resources :employees

  get 'customers/search' => 'customers#search', as: :search_customers
  resources :customers

  resources :sessions, only: [:new, :create, :destroy]

  root 'sessions#home', as: :home
  get 'signin' => 'sessions#new'
  get 'signout' => 'sessions#destroy', via: 'delete'
  
  get 'reports' => 'reports#home'
  get 'reports/purchases' => 'reports#purchases'
  get 'reports/redemptions' => 'reports#redemptions'
  get 'reports/adjustments' => 'reports#adjustments'
  get 'reports/customers' => 'reports#customers'

end

app/models/redemption.rb
class Redemption < ActiveRecord::Base
  belongs_to :customer
  belongs_to :employee

  # Validations
  validates :customer_id, presence: true
  validates :employee_id, presence: true
  validates :date, presence: true
  validates :amount, presence: true

  @@discounts = [
  	10,
  	20,
  	05
  ]

  @@discount = 10

  def self.discounts
  	@@discounts
  end

  def self.discount
  	@@discount
  end

  def self.discount=(new_discount)
    @@discount = new_discount
  end

  def self.report(redemptions, options = {})
    CSV.generate(options) do |csv|
      csv << ["Customer First Name", "Customer Last Name", "Customer Email",
        "Points Redeemed", "Employee Last Name", "Date"]
      redemptions.each do |redemption|
        csv << [redemption.customer.fname, redemption.customer.lname,
          redemption.customer.email, redemption.amount,
          redemption.employee.lname, redemption.date.strftime("%m/%d/%Y")]
      end
    end
  end
end

app/controllers/redemptions_controller.rb
class RedemptionsController < ApplicationController
  before_action :set_redemption, only: [:show, :edit, :update, :destroy]
  before_action :must_be_employee

  # GET /redemptions
  # GET /redemptions.json
  def index
    @redemptions = Redemption.all
  end

  # GET /redemptions/1
  # GET /redemptions/1.json
  def show
  end

  # GET /redemptions/new
  def new
    if params[:customer_id]
      @customer = Customer.find_by_id(params[:customer_id])
      @customer && @redemption = @customer.redemptions.build
    else
      flash.now[:error] = "Something is wrong."
      redirect_to home_path; return
    end
    @redemption.employee = current_user
  end

  # GET /redemptions/1/edit
  def edit
  end

  # POST /redemptions
  # POST /redemptions.json
  def create
    @redemption = Redemption.new(redemption_params)

    @customer = @redemption.customer

    if params[:customer][:password] != @customer.password
      flash.now[:error] = 'Incorrect password for customer.'
      render :new; return
    end

    points_redeemed = @redemption.amount
    old_points_balance = @customer.current_points
    new_points_balance = old_points_balance - points_redeemed

    if new_points_balance < 0
      flash.now[:error] = 'Not enough customer points'
      render :new; return
    end

    @customer.update(current_points: new_points_balance)

    respond_to do |format|
      if @redemption.save
        format.html { redirect_to @redemption.customer, notice: 'Redemption successful; points deducted.' }
        format.json { render :show, status: :created, location: @redemption }
      else
        format.html { render :new }
        format.json { render json: @redemption.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /redemptions/1
  # PATCH/PUT /redemptions/1.json
  def update
    respond_to do |format|
      if @redemption.update(redemption_params)
        format.html { redirect_to @redemption, notice: 'Redemption was successfully updated.' }
        format.json { render :show, status: :ok, location: @redemption }
      else
        format.html { render :edit }
        format.json { render json: @redemption.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /redemptions/1
  # DELETE /redemptions/1.json
  def destroy
    @redemption.destroy
    respond_to do |format|
      format.html { redirect_to redemptions_url, notice: 'Redemption was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def update_discount
    Redemption.discount = params[:discount]
    redirect_to home_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_redemption
      @redemption = Redemption.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def redemption_params
      params.require(:redemption).permit(:customer_id, :employee_id, :date, :amount)
    end
end

app/helpers/redemptions_helper.rb
module RedemptionsHelper
end

app/views/redemptions/_form.html.erb
<%= form_for(@redemption) do |f| %>
  <% if @redemption.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@redemption.errors.count, "error") %> prohibited this redemption from being saved:</h2>

      <ul>
      <% @redemption.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>Customer <%= @customer %> has <%= @customer.current_points %> points available.</p>

  <%= f.hidden_field :customer_id %>
  <%= f.hidden_field :employee_id %>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date, order: [:month, :day, :year] %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.number_field :amount, id: "redemption_amount" %>
  </div>
  <div class="field">
    <%= label :customer, :password, "Customer's password" %><br>
    <%= text_field :customer, :password, value: "" %>
  </div>
  <%= f.hidden_field :discount, value: Redemption.discount, id: :discount %>
  <p>This transaction is worth $<span id="redemption_worth">0</span>.</p>
  <div class="actions">
    <%= f.submit value: "Redeem" %>
  </div>
<% end %>

app/views/redemptions/edit.html.erb
<h1>Editing redemption</h1>

<%= render 'form' %>

<%= link_to 'Show', @redemption %> |
<%= link_to 'Back', redemptions_path %>

app/views/redemptions/edit_discount.html.erb
<h1>Manager Point to Dollar Conversion Rate</h1>

<p>The current Point to Dollar conversion rate is <%= Redemption.discount %>%</p>

<%= form_tag(update_discount_path, method: :put) do %>
	<div class="field">
		<%= label_tag :discount, "Modify point to dollar conversion rate" %>
		<%= select_tag :discount, options_for_select(Redemption.discounts, Redemption.discount) %>
	</div>
	<div class="actions">
		<%= submit_tag %>
	</div>
<% end %>

app/views/redemptions/index.html.erb
<h1>Listing redemptions</h1>

<table>
  <thead>
    <tr>
      <th>Customer</th>
      <th>Date</th>
      <th>Amount</th>
      <th>Discount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @redemptions.each do |redemption| %>
      <tr>
        <td><%= redemption.customer %></td>
        <td><%= redemption.date %></td>
        <td><%= redemption.amount %></td>
        <td><%= redemption.discount %></td>
        <td><%= link_to 'Show', redemption %></td>
        <td><%= link_to 'Edit', edit_redemption_path(redemption) %></td>
        <td><%= link_to 'Destroy', redemption, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Redemption', new_redemption_path %>

app/views/redemptions/new.html.erb
<h1>Existing Customer Redeem Points</h1>

<%= render 'form' %>

app/views/redemptions/show.html.erb
<p>
  <strong>Customer:</strong>
  <%= @redemption.customer %>
</p>

<p>
  <strong>Date:</strong>
  <%= @redemption.date %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @redemption.amount %>
</p>

<p>
  <strong>Discount:</strong>
  <%= @redemption.discount %>
</p>

<%= link_to 'Edit', edit_redemption_path(@redemption) %> |
<%= link_to 'Back', redemptions_path %>