config/routes.rb
Rails.application.routes.draw do

  get 'redemptions/edit_discount' => 'redemptions#edit_discount', as: :edit_discount
  put 'redemptions/update_discount' => 'redemptions#update_discount', as: :update_discount
  resources :redemptions

  resources :purchases

  resources :adjustments

  resources :employees

  get 'customers/search' => 'customers#search', as: :search_customers
  resources :customers

  resources :sessions, only: [:new, :create, :destroy]

  root 'sessions#home', as: :home
  get 'signin' => 'sessions#new'
  get 'signout' => 'sessions#destroy', via: 'delete'
  
  get 'reports' => 'reports#home'
  get 'reports/purchases' => 'reports#purchases'
  get 'reports/redemptions' => 'reports#redemptions'
  get 'reports/adjustments' => 'reports#adjustments'
  get 'reports/customers' => 'reports#customers'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/associate_home.html.erb
<h1>Associate Home Page</h1>

<p>Select an option:</p>
<ol>
	<li><%= link_to "New Customer", new_customer_path %></li>
	<li><%= link_to "Existing Customer", search_customers_path %></li>
</ol>

app/views/static_pages/manager_home.html.erb
<h1>Manager Home Page</h1>

<p>Select an option:</p>
<ol>
	<li><%= link_to "New Customer", new_customer_path %></li>
	<li><%= link_to "Existing Customer", search_customers_path %></li>
	<li><%= link_to "New Employee", new_employee_path %></li>
	<li><%= link_to "Manage Employees", employees_path %></li>
	<li><%= link_to "Point to Dollar Conversion Rate", edit_discount_path %></li>
	<li><%= link_to "Reports", reports_path %></li>
</ol>