config/routes.rb
Rails.application.routes.draw do

  get 'redemptions/edit_discount' => 'redemptions#edit_discount', as: :edit_discount
  put 'redemptions/update_discount' => 'redemptions#update_discount', as: :update_discount
  resources :redemptions

  resources :purchases

  resources :adjustments

  resources :employees

  get 'customers/search' => 'customers#search', as: :search_customers
  resources :customers

  resources :sessions, only: [:new, :create, :destroy]

  root 'sessions#home', as: :home
  get 'signin' => 'sessions#new'
  get 'signout' => 'sessions#destroy', via: 'delete'
  
  get 'reports' => 'reports#home'
  get 'reports/purchases' => 'reports#purchases'
  get 'reports/redemptions' => 'reports#redemptions'
  get 'reports/adjustments' => 'reports#adjustments'
  get 'reports/customers' => 'reports#customers'

end

app/models/customer.rb
class Customer < ActiveRecord::Base

	has_many :purchases
	has_many :redemptions
	has_many :adjustments

	after_initialize :init

	# Validations
	validates :fname, presence: true, length: {maximum: 25}
	validates :lname, presence: true, length: {maximum: 25}
	validates :email, presence: true, length: {maximum: 50}
	validates :email2, length: {maximum: 50}
	validates :email3, length: {maximum: 50}
	validates :address, length: {maximum: 25}
	validates :city, length: {maximum: 25}
	validates :state, length: {is: 2}, allow_blank: true
	validates :zip, length: {is: 5}, allow_blank: true
	validates :twitter, length: {maximum: 30}
	validates :dob, length: {is: 10}, allow_blank: true
	validates :dlnumber, length: {maximum: 8}
	validates :lifetime_points, presence: true, length: {maximum: 10}
	validates :current_points, presence: true, length: {maximum: 10}
	validates :password, presence: true, length: {maximum: 10}


	def authenticate(pass)
		pass == self.password
	end

	def to_s
		"#{self.fname} #{self.lname}"
	end

  def self.report(customers, options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      customers.each do |customer|
        csv << customer.attributes.values_at(*column_names)
      end
    end
  end

	private

		def init
			self.lifetime_points ||= 0
			self.current_points ||= 0
			self.city ||= "Houston"
			self.state ||= "TX"
			self.password ||= "12345"
		end

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]
  before_action :must_be_employee, except: [:show]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
    if signed_in_associate?
      render 'show_associate'
    elsif signed_in_manager?
      render 'show_manager'
    end
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)
    @customer.pass_date = Date.today

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    if customer_params[:password] != @customer.password
      customer.pass_date = Date.today
    end
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    if not params[:email].blank?
      @customer = Customer.find_by(email: params[:email])
    elsif not params[:lname].blank?
      @customer = Customer.find_by(lname: params[:lname])
    else
      render :search; return
    end

    if @customer
      redirect_to @customer
    else
      flash.now[:error] = "Customer not found"
      render :search
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:fname, :lname, :email, :email2, :email3, :phone, :phone2, :address, :city, :state, :zip, :twitter, :dob, :dlnumber, :lifetime_points, :current_points, :password, :pass_date)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="customer_form">
    <div class="fields_1">
      <div class="field">
        <%= f.label :fname, required: :required %><br>
        <%= f.text_field :fname, required: :required, validate: true %>
      </div>
      <div class="field">
        <%= f.label :lname, required: :required %><br>
        <%= f.text_field :lname, required: :required %>
      </div>
      <div class="field">
        <%= f.label :email, required: :required %><br>
        <%= f.email_field :email, required: :required %>
      </div>
      <div class="field">
        <%= f.label :email2 %><br>
        <%= f.email_field :email2 %>
      </div>
      <div class="field">
        <%= f.label :email3 %><br>
        <%= f.email_field :email3 %>
      </div>
      <div class="field">
        <%= f.label :phone %><br>
        <%= f.text_field :phone %>
      </div>
      <div class="field">
        <%= f.label :phone2 %><br>
        <%= f.text_field :phone2 %>
      </div>
      <div class="field">
        <%= f.label :twitter %><br>
        <%= f.text_field :twitter %>
      </div>
      <div class="field">
        <%= f.label :dob %><br>
        <%= f.text_field :dob %>
      </div>
      <div class="field">
        <%= f.label :dlnumber %><br>
        <%= f.number_field :dlnumber %>
      </div>
    </div>
    <div class="fields_2">
      <div class="field">
        <%= f.label :address %><br>
        <%= f.text_field :address %>
      </div>
      <div class="field">
        <%= f.label :city %><br>
        <%= f.text_field :city %>
      </div>
      <div class="field">
        <%= f.label :state %><br>
        <%= f.text_field :state %>
      </div>
      <div class="field">
        <%= f.label :zip %><br>
        <%= f.number_field :zip %>
      </div>
      <div class="field password">
        <p>Please verify all entered information and enter a personal password below:</p>
        <%= f.label :password, required: :required %><br>
        <%= f.text_field :password, required: :required %>
      </div>
      <%= f.hidden_field :pass_date, value: Date.today %>
      <div class="actions">
        <%= f.submit %>
      </div>
    </div>
  </div>
<% end %>

app/views/customers/_purchases.html.erb
<h2>Purchase History</h2>

<table class="table table-hover">
  <thead>
    <th>Date</th>
    <th>Total Amount</th>
  </thead>
  <tbody>
  <% @customer.purchases.order("date DESC").each do |purchase| %>
    <tr>
      <td><%= purchase.date.strftime("%m/%d/%Y") %></td>
      <td><%= number_to_currency(purchase.amount) %></td>
    </tr>
  <% end %>    
  </tbody>
</table>

app/views/customers/_redemptions.html.erb
<h2>Points Redemption History</h2>

<table class="table table-hover">
  <thead>
    <th>Date</th>
    <th>Points Redeemed</th>
  </thead>
  <tbody>
  <% @customer.redemptions.order("date DESC").each do |redemption| %>
    <tr>
      <td><%= redemption.date.strftime("%m/%d/%Y") %></td>
      <td><%= redemption.amount %></td>
  <% end %>    
  </tbody>
</table>

app/views/customers/edit.html.erb
<h1>Existing Customer Edit Information</h1>

<%= render 'form' %>

app/views/customers/index.html.erb
<h1>Listing customers</h1>

<table>
  <thead>
    <tr>
      <th>Fname</th>
      <th>Lname</th>
      <th>Email</th>
      <th>Email2</th>
      <th>Email3</th>
      <th>Phone</th>
      <th>Phone2</th>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th>Twitter</th>
      <th>Dob</th>
      <th>Dlnumber</th>
      <th>Lifetime points</th>
      <th>Current points</th>
      <th>Password</th>
      <th>Pass date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.fname %></td>
        <td><%= customer.lname %></td>
        <td><%= customer.email %></td>
        <td><%= customer.email2 %></td>
        <td><%= customer.email3 %></td>
        <td><%= customer.phone %></td>
        <td><%= customer.phone2 %></td>
        <td><%= customer.address %></td>
        <td><%= customer.city %></td>
        <td><%= customer.state %></td>
        <td><%= customer.zip %></td>
        <td><%= customer.twitter %></td>
        <td><%= customer.dob %></td>
        <td><%= customer.dlnumber %></td>
        <td><%= customer.lifetime_points %></td>
        <td><%= customer.current_points %></td>
        <td><%= customer.password %></td>
        <td><%= customer.pass_date %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>New Customer Information Page</h1>

<%= render 'form' %>

app/views/customers/search.html.erb
<h1>Search for Existing Customer</h1>

<p>Search by Last Name or Email</p>

<%= form_tag(search_customers_path, method: :get) do  %>
	<div class="field">
		<%= label_tag :lname, "Last Name" %><br>
		<%= text_field_tag :lname %>
	</div>
	<div class="field">
		<%= label_tag :email, "Email" %><br>
		<%= text_field_tag :email %>
	</div>
	<div class="actions">
		<%= submit_tag :Search %>
	</div>
<% end %>

app/views/customers/show.html.erb
<h1>Customer Detail Page</h1>

<div class="customer_details">
	<p>Welcome <%= @customer %>!</p>
	<p>You have <%= @customer.current_points %> points available.</p>
	<p>Lifetime points: <%= @customer.lifetime_points %></p>
</div>

<div class="customer_tables">
		<div class="purchases_table">
			<%= render 'purchases' %>
		</div>
		<div class="redemptions_table">
			<%= render 'redemptions' %>
		</div>
</div>

<p>Please contact Vapor Lair with any concerns. Thank you for being a valuable customer!</p>

app/views/customers/show_associate.html.erb
<h1>Associate Existing Customer Main Page</h1>

<div class="customer_details">
	<p><%= @customer %></p>
	<p>Current points: <%= @customer.current_points %></p>
	<p>Lifetime points: <%= @customer.lifetime_points %></p>
	<%= link_to 'Edit Customer', edit_customer_path(@customer), class: 'edit_customer btn btn-primary' %>
</div>

<div class="customer_tables">
		<div class="purchases_table">
			<%= render 'purchases' %>
		</div>
		<div class="redemptions_table">
			<%= render 'redemptions' %>
		</div>
</div>
<div class="customer_actions">
	<div class="purchases_actions">
		<p><%= link_to 'Add New Purchase', new_purchase_path(customer_id: @customer.id) %></p>
	</div>
	<div class="redemptions_actions">
		<p><%= link_to 'Redeem Points', new_redemption_path(customer_id: @customer.id) %></p>
	</div>
</div>

app/views/customers/show_manager.html.erb
<h1>Manager Existing Customer Main Page</h1>

<div class="customer_details">
	<p><%= @customer %></p>
	<p>Current points: <%= @customer.current_points %></p>
	<p>Lifetime points: <%= @customer.lifetime_points %></p>
	<%= link_to 'Edit Customer', edit_customer_path(@customer), class: 'edit_customer btn btn-primary' %>
</div>

<div class="customer_tables">
		<div class="purchases_table">
			<%= render 'purchases' %>
		</div>
		<div class="redemptions_table">
			<%= render 'redemptions' %>
		</div>
</div>
<div class="customer_actions">
	<div class="purchases_actions">
		<p><%= link_to 'Add New Purchase', new_purchase_path(customer_id: @customer.id) %></p>
	</div>
	<div class="redemptions_actions">
		<p><%= link_to 'Modify Points', new_adjustment_path(customer_id: @customer.id) %></p>
		<p><%= link_to 'Redeem Points', new_redemption_path(customer_id: @customer.id) %></p>
	</div>
</div>