config/routes.rb
Rails.application.routes.draw do

  get 'redemptions/edit_discount' => 'redemptions#edit_discount', as: :edit_discount
  put 'redemptions/update_discount' => 'redemptions#update_discount', as: :update_discount
  resources :redemptions

  resources :purchases

  resources :adjustments

  resources :employees

  get 'customers/search' => 'customers#search', as: :search_customers
  resources :customers

  resources :sessions, only: [:new, :create, :destroy]

  root 'sessions#home', as: :home
  get 'signin' => 'sessions#new'
  get 'signout' => 'sessions#destroy', via: 'delete'
  
  get 'reports' => 'reports#home'
  get 'reports/purchases' => 'reports#purchases'
  get 'reports/redemptions' => 'reports#redemptions'
  get 'reports/adjustments' => 'reports#adjustments'
  get 'reports/customers' => 'reports#customers'

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

	before_action :must_be_manager

	def home
	end

	def purchases
		if params[:commit] || params[:csv]
			@purchases = Purchase.all
			@title = "Viewing purchases"
			from, to, employee = [params[:from], params[:to], params[:employee]]
			
			unless from.blank?
				@purchases = @purchases.where("date >= ?", from)
				@title += " from #{from}"
			end

			unless to.blank?
				@purchases = @purchases.where("date <= ?", to)
				@title += " to #{to}"
			end

			unless employee.blank?
				@purchases = @purchases.where("employee_id = ?", employee)
				@title += " with employee #{Employee.find_by_id(employee)}"
			end

			@purchases = @purchases.order("date DESC")

			if params[:csv]
				send_data Purchase.report(@purchases), filename: "purchases_report.csv"
			else
				render :purchases_results
			end
		else
			render :purchases
		end
	end

	def redemptions
		if params[:commit] || params[:csv]
			@redemptions = Redemption.all
			@title = "Viewing redemptions"
			from, to, employee = [params[:from], params[:to], params[:employee]]
			
			unless from.blank?
				@redemptions = @redemptions.where("date >= ?", from)
				@title += " from #{from}"
			end

			unless to.blank?
				@redemptions = @redemptions.where("date <= ?", to)
				@title += " to #{to}"
			end

			unless employee.blank?
				@redemptions = @redemptions.where("employee_id = ?", employee)
				@title += " with employee #{Employee.find_by_id(employee)}"
			end

			@redemptions = @redemptions.order("date DESC")

			if params[:csv]
				send_data Redemption.report(@redemptions), filename: "redemptions_report.csv"
			else
				render :redemptions_results
			end
		else
			render :redemptions
		end
	end

	def adjustments
		if params[:commit] || params[:csv]
			@adjustments = Adjustment.all
			@title = "Viewing adjustments"
			from, to, reason = [params[:from], params[:to], params[:reason]]
			
			unless from.blank?
				@adjustments = @adjustments.where("date >= ?", from)
				@title += " from #{from}"
			end

			unless to.blank?
				@adjustments = @adjustments.where("date <= ?", to)
				@title += " to #{to}"
			end

			unless reason.blank?
				@adjustments = @adjustments.where("reason = ?", reason)
				@title += " with reason \"#{reason}\""
			end

			@adjustments = @adjustments.order("created_at DESC")

			if params[:csv]
				send_data Adjustment.report(@adjustments), filename: "adjustments_report.csv"
			else
				render :adjustments_results
			end
		else
			render :adjustments
		end
	end

	def customers
		if params[:commit] || params[:csv]
			@customers = Customer.all
			@title = "Viewing customers"
			from = params[:from]
			
			unless from.blank?
				@customers = Purchase.where("date > ?", from).map { |purchase| purchase.customer }.uniq
				@title += " with purchases more recent than #{from}"
			end

			if params[:csv]
				send_data Customer.report(@customers), filename: "customers_report.csv"
			else
				render :customers_results
			end
		else
			render :customers
		end
	end

end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/adjustments.html.erb
<h1>Points Modification Report</h1>
<h3>Select your criteria</h3>

<%= form_tag reports_adjustments_path, method: :get do %>

	<div class="fields date_range">
		<h4>Date Range</h4>
		<div class="field">
			<%= label_tag :from, "From" %><br>
			<%= date_field_tag :from %>
		</div>
		<div class="field">
			<%= label_tag :to, "To" %><br>
			<%= date_field_tag :to %>			
		</div>
		<div class="field">
			<%= label_tag :reason, "Reason (leave blank for all)" %><br>
			<%= select_tag :reason, options_for_select(Adjustment.reasons), {include_blank: true} %>
		</div>
		<div class="actions">
			<%= submit_tag "Generate" %>
			<%= submit_tag "Export as CSV", name: :csv %>
		</div>
	</div>

<% end %>

app/views/reports/adjustments_results.html.erb
<h1>Points Modified Report</h1>
<h3><%= @title %></h3>

<div class="table_area">
	<table class="table table-hover">
		<thead>
			<th>Customer First Name</th>
			<th>Customer Last Name</th>
			<th>Customer Email</th>
			<th>Adjustment Amount</th>
			<th>Employee Last Name</th>
			<th>Date</th>
		</thead>
		<tbody>
		<% @adjustments.each do |adjustment| %>
	    <tr>
	      <td><%= adjustment.customer.fname %></td>
	      <td><%= adjustment.customer.lname %></td>
	      <td><%= adjustment.customer.email %></td>
	      <td><%= adjustment.change %></td>
	      <td><%= adjustment.employee.lname %></td>
	      <td><%= adjustment.created_at.strftime("%m/%d/%Y") %></td>
	     </tr>
	  <% end %>    
	  </tbody>
	</table>
</div>

app/views/reports/customers.html.erb
<h1>Customer Listing Report</h1>
<h3>Select your criteria</h3>

<%= form_tag reports_customers_path, method: :get do %>

	<div class="fields date_range">
		<h4>Date of Last Purchase</h4>
		<div class="field">
			<%= label_tag :from, "More recent than" %><br>
			<%= date_field_tag :from %>
		</div>
		<div class="actions">
			<%= submit_tag "Generate" %>
			<%= submit_tag "Export as CSV", name: :csv %>
		</div>
	</div>

<% end %>

app/views/reports/customers_results.html.erb
<h1>Customer Listing Report</h1>
<h3><%= @title %></h3>

<div class="table_area">
	<table class="table table-hover">
		<thead>
			<th>First Name</th>
			<th>Last Name</th>
			<th>Email</th>
			<th>Email 2</th>
			<th>Email 3</th>
			<th>Phone</th>
			<th>Phone 2</th>
			<th>Twitter</th>
			<th>Address</th>
			<th>City</th>
			<th>State</th>
			<th>ZIP</th>
			<th>DOB</th>
			<th>DL Number</th>
			<th>Current Points</th>
			<th>Lifetime Points</th>
			<th>Password</th>
			<th>Password Date</th>
		</thead>
		<tbody>
		<% @customers.each do |customer| %>
	    <tr>
	      <td><%= customer.fname %></td>
	      <td><%= customer.lname %></td>
	      <td><%= customer.email %></td>
	      <td><%= customer.email2 %></td>
	      <td><%= customer.email3 %></td>
	      <td><%= customer.phone %></td>
	      <td><%= customer.phone2 %></td>
	      <td><%= customer.twitter %></td>
	      <td><%= customer.address %></td>
	      <td><%= customer.city %></td>
	      <td><%= customer.state %></td>
	      <td><%= customer.zip %></td>
	      <td><%= customer.dob %></td>
	      <td><%= customer.dlnumber %></td>
	      <td><%= customer.current_points %></td>
	      <td><%= customer.lifetime_points %></td>
	      <td><%= customer.password %></td>
	      <td><%= customer.pass_date %></td>
	    </tr>
	  <% end %>    
	  </tbody>
	</table>
</div>

app/views/reports/home.html.erb
<h1>Reports Main Page</h1>

<h2>Select a report</h2>
<ol>
	<li><%= link_to 'Purchases', reports_purchases_path %></li>
	<li><%= link_to 'Points Redemption', reports_redemptions_path %></li>
	<li><%= link_to 'Points Modification', reports_adjustments_path %></li>
	<li><%= link_to 'Customer Listing', reports_customers_path %></li>
</ol>

app/views/reports/purchases.html.erb
<h1>Purchases Report</h1>
<h3>Select your criteria</h3>

<%= form_tag reports_purchases_path, method: :get do %>

	<div class="fields date_range">
		<h4>Date Range</h4>
		<div class="field">
			<%= label_tag :from, "From" %><br>
			<%= date_field_tag :from %>
		</div>
		<div class="field">
			<%= label_tag :to, "To" %><br>
			<%= date_field_tag :to %>			
		</div>
		<div class="field">
			<%= label_tag :employee, "Employee (leave blank for all)" %><br>
			<%= select_tag :employee, options_from_collection_for_select(Employee.all, :id, :to_s), {include_blank: true} %>
		</div>
		<div class="actions">
			<%= submit_tag "Generate" %>
			<%= submit_tag "Export as CSV", name: :csv %>
		</div>
	</div>

<% end %>

app/views/reports/purchases_results.html.erb
<h1>Purchases Report</h1>
<h3><%= @title %></h3>

<div class="table_area">
	<table class="table table-hover">
		<thead>
			<th>Customer First Name</th>
			<th>Customer Last Name</th>
			<th>Customer Email</th>
			<th>Purchase Amount</th>
			<th>Employee Last Name</th>
			<th>Date</th>
		</thead>
		<tbody>
		<% @purchases.each do |purchase| %>
	    <tr>
	      <td><%= purchase.customer.fname %></td>
	      <td><%= purchase.customer.lname %></td>
	      <td><%= purchase.customer.email %></td>
	      <td><%= number_to_currency(purchase.amount) %></td>
	      <td><%= purchase.employee.lname %></td>
	      <td><%= purchase.date.strftime("%m/%d/%Y") %></td>
	     </tr>
	  <% end %>    
	  </tbody>
	</table>
</div>

app/views/reports/redemptions.html.erb
<h1>Points Redeemed Report</h1>
<h3>Select your criteria</h3>

<%= form_tag reports_redemptions_path, method: :get do %>

	<div class="fields date_range">
		<h4>Date Range</h4>
		<div class="field">
			<%= label_tag :from, "From" %><br>
			<%= date_field_tag :from %>
		</div>
		<div class="field">
			<%= label_tag :to, "To" %><br>
			<%= date_field_tag :to %>			
		</div>
		<div class="field">
			<%= label_tag :employee, "Employee (leave blank for all)" %><br>
			<%= select_tag :employee, options_from_collection_for_select(Employee.all, :id, :to_s), {include_blank: true} %>
		</div>
		<div class="actions">
			<%= submit_tag "Generate" %>
			<%= submit_tag "Export as CSV", name: :csv %>
		</div>
	</div>

<% end %>

app/views/reports/redemptions_results.html.erb
<h1>Points Redeemed Report</h1>
<h3><%= @title %></h3>

<div class="table_area">
	<table class="table table-hover">
		<thead>
			<th>Customer First Name</th>
			<th>Customer Last Name</th>
			<th>Customer Email</th>
			<th>Points Redeemed</th>
			<th>Employee Last Name</th>
			<th>Date</th>
		</thead>
		<tbody>
		<% @redemptions.each do |redemption| %>
	    <tr>
	      <td><%= redemption.customer.fname %></td>
	      <td><%= redemption.customer.lname %></td>
	      <td><%= redemption.customer.email %></td>
	      <td><%= redemption.amount %></td>
	      <td><%= redemption.employee.lname %></td>
	      <td><%= redemption.date.strftime("%m/%d/%Y") %></td>
	     </tr>
	  <% end %>    
	  </tbody>
	</table>
</div>